tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "secondary": "#904d00",
                "on-primary-container": "#7a88a7",
                "on-tertiary": "#ffffff",
                "on-tertiary-fixed": "#2a1800",
                "on-primary-fixed-variant": "#394763",
                "error-container": "#ffdad6",
                "inverse-on-surface": "#f2f1ec",
                "surface": "#fbf9f4",
                "surface-dim": "#dbdad5",
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                "tertiary-container": "#301c00",
                "on-background": "#1b1c19",
                "secondary-fixed": "#ffdcc3",
                "on-primary-fixed": "#0d1b35",
                "outline": "#75777e",
                "error": "#ba1a1a",
                "tertiary-fixed": "#ffddb5",
                "on-secondary-fixed-variant": "#6e3900",
                "on-secondary-fixed": "#2f1500",
                "on-surface-variant": "#45474d",
                "inverse-primary": "#b9c6e8",
                "secondary-container": "#fe932c",
                "primary-container": "#12203a",
                "primary-fixed": "#d8e2ff",
                "primary": "#00081d",
                "outline-variant": "#c5c6ce",
                "surface-container-low": "#f5f3ee",
                "on-tertiary-container": "#a28259",
                "tertiary-fixed-dim": "#e6c093",
                "primary-fixed-dim": "#b9c6e8",
                "surface-bright": "#fbf9f4",
                "on-secondary-container": "#663500",
                "surface-container-highest": "#e4e2dd",
                "surface-tint": "#515e7c",
                "on-tertiary-fixed-variant": "#5c421f",
                "on-secondary": "#ffffff",
                "surface-container": "#f0eee9",
                "tertiary": "#100700",
                "on-error": "#ffffff",
                "on-primary": "#ffffff",
                "secondary-fixed-dim": "#ffb77d",
                "surface-variant": "#e4e2dd",
                "background": "#fbf9f4",
                "inverse-surface": "#30312e",
                "surface-container-high": "#eae8e3",
                "on-surface": "#1b1c19"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "unit": "4px",
                "gutter": "24px",
                "margin-desktop": "64px",
                "section-gap": "120px",
                "margin-mobile": "20px"
            },
            "fontFamily": {
                "display-lg": ["Playfair Display"],
                "body-md": ["Inter"],
                "headline-sm": ["Playfair Display"],
                "body-lg": ["Inter"],
                "label-sm": ["Inter"],
                "statement-caps": ["Inter"],
                "headline-md": ["Playfair Display"],
                "display-lg-mobile": ["Playfair Display"]
            },
            "fontSize": {
                "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
                "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "label-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }],
                "statement-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.2em", "fontWeight": "600" }],
                "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "500" }],
                "display-lg-mobile": ["36px", { "lineHeight": "1.1", "fontWeight": "600" }]
            }
        },
    },
};
